account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('user_data/', views.user_data),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
]

djangovue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from restmanual import views as restmanual

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('api/', include('listelement.urls')),
    path('comment/', include('comment.urls')),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('store.urls')),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
    ),
    path('restmanual/demo',restmanual.manualJson),
    path('restmanual/', include('restmanual.urls')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

store/urls.py
from django.urls import path, include
from . import views

from django.contrib.sitemaps.views import sitemap
from .sitemap import ElementSitemap

sitemaps = {
    'sitemap': ElementSitemap
}

app_name='store'
urlpatterns = [
    path('', views.index, name='index'),
    path('product/pay/paypal/<int:pk>', views.make_pay_paypal, name='make_pay_paypal'),
    path('product/pay/paypal/<int:pk>/<str:code>', views.make_pay_paypal, name='make_pay_paypal'),
    path('product/paypal/success/<int:pk>', views.paypal_success, name='paypal_success'),
    path('product/paypal/success/<int:pk>/<str:code>', views.paypal_success, name='paypal_success'),
    path('product/paypal/cancel', views.paypal_cancel, name='paypal_cancel'),

    path('bought', views.bought, name='bought'),

    path('product/payed/detail/<int:pk>', views.detail_pay, name='detail_pay'),
    
    path('product/<int:pk>',views.DetailView.as_view(), name='detail'),
    #path('product/<slug:url_clean>',views.DetailView.as_view(), name='detail'),
    path('product/coupon_apply',views.coupon_apply, name='coupon_apply'),
    path('product/<slug:url_clean>',views.detail, name='detail'),
    path('product/<slug:url_clean>/<str:code>',views.detail, name='detail'),

    #carrito
    path('cart_detail', views.cart_detail, name='cart_detail'),
    path('cart_size', views.cart_size, name='cart_size'),
    path('cart_remove/<int:pk>', views.cart_remove, name='cart_remove'),
    path('add_to_cart/<int:pk>', views.add_to_cart, name='add_to_cart'),
    
    #path('product/<int:pk>/<slug:url_clean>',views.DetailView.as_view(), name='detail'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

account/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='user/avatar')

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions

from django.utils.translation import gettext as _

from .models import UserProfile

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Email', 
    max_length=50,
    help_text=_('Put your favorite email'),
    error_messages={'invalid':"Solamente puedes colocar caracteres válidos para un email"})

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        u = User.objects.filter(email = email)
        if u.count():
            raise ValidationError(_("Email taking"))
        return email

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar','user')
        
    def __init__(self,*args,**kwargs):
        super(UserProfileForm, self).__init__(*args,**kwargs)
        self.fields['user'].widget = forms.HiddenInput()
        self.fields['user'].required = False
        self.fields['avatar'].widget.attrs['class'] = "custom-file-input"
        self.fields['avatar'].widget.attrs['id'] = "customFile"
    
    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        w, h = get_image_dimensions(avatar)

        print(len(avatar))

        #validacion por tamano de la img
        max_width = max_height = 600
        if w > max_width or h > max_height:
            raise forms.ValidationError("Imagen muy grande, la imagen no puede superar las %spx, %spx" % (max_width, max_height))
        
        # extension
        m,t = avatar.content_type.split('/')
        if not(m == 'image' and t in ['jpeg', 'jpg', 'gif', 'png']):
            raise forms.ValidationError("Imagen no soportada, solamente soportamos: 'jpeg', 'jpg', 'gif', 'png'")
        
        #tamano de la imagen 1 KB equivale a 1024B
        if len(avatar) > (30 * 1024):
            raise forms.ValidationError("Imagen no puede superar los 30kb")

        return avatar

account/views.py
import os

from django.conf import settings

from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
#from django.contrib.auth.forms import UserCreationForm
#from .forms.CustomUserCreationForm import CustomUserCreationForm # con carpeta

from django.contrib.auth import login as make_login
from django.core.exceptions import ObjectDoesNotExist

from .forms import CustomUserCreationForm, UserProfileForm
from .models import UserProfile

# Create your views here.

def user_data(request):
    print(request.user.username)
    print(request.user.is_authenticated)
    return render(request,'user_data.html')

@login_required
def profile(request):
    #print(request.user.id)
    form = UserProfileForm()
    if request.method == 'POST':
        pathOldAvatar = None
        
        try:
            userprofile = UserProfile.objects.get(user=request.user)
            form = UserProfileForm(request.POST, request.FILES, instance=userprofile)

            #path del avata anterior
            pathOldAvatar = os.path.join(settings.MEDIA_ROOT,userprofile.avatar.name)

        except ObjectDoesNotExist:
            form = UserProfileForm(request.POST, request.FILES)
        
        if form.is_valid():

            #borrar avatar anterior si existe un perfil
            if pathOldAvatar is not None and os.path.isfile(pathOldAvatar):
                os.remove(pathOldAvatar)

            userprofile = form.save(commit=False)
            userprofile.user = request.user
            userprofile.save()


    return render(request,'profile.html',{'form':form})

def register(request):
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                make_login(request, user)
                return redirect(reverse('account:profile'))

            #return redirect(reverse('login'))

    return render(request,'register.html',{'form':form})

account/templates/profile.html
{% extends "base.html" %}

{% load bootstrap %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}

<div class="card">
    <div class="card-header">
        Perfil
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-md-4 offset-md-4">

                {% if user.userprofile %}
                    <img id="iavatar" class="img-fluid" src="{{ MEDIA_URL }}{{ user.userprofile.avatar }}">
                {% else %}
                    <img id="iavatar" class="img-fluid" src="{% static 'img/logo.png' %}">
                {% endif %}

                Thumbanail
                {% load thumbnail %}
                <img src="{{ user.userprofile.avatar|thumbnail_url:'avatar' }}" alt="" />
                <br>

                {% thumbnail user.userprofile.avatar 200x200 upscale as thumb %}
                <img src="{{ thumb.url }}"
                    width="{{ thumb.width }}"
                    height="{{ thumb.height }}" />
            </div>
        </div>



        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="post" enctype="multipart/form-data" id="favatar">

                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>

                    {% csrf_token %}
                    {{ form.user }}

                    <!--<input type="submit" value="Enviar" class="btn btn-success">-->
                </form>
            </div>
        </div>

        <table class="table table-borderless">

            <tbody>
                <tr>
                    <th>Usuario</th>
                    <td>{{ user.username }}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <th>Autenticado</th>
                    <td>{{ user.is_authenticated }}</td>
                </tr>
                <tr>
                    <th>Anónimo</th>
                    <td>{{ user.is_anonymous }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


{% else %}
<p><a href="{% url 'login' %}">Login</a></p>
{% endif %}

<script>

    document.getElementById("customFile").addEventListener("change", function () {
        filename = this.value.split("\\").pop()
        this.nextElementSibling.textContent = filename
        document.getElementById("favatar").submit()
    })

    document.getElementById("iavatar").onclick = function(){
        document.getElementById("customFile").click()
    }
</script>

{% endblock %}

account/templates/register.html
{% extends "base_user_account.html" %}

{% load bootstrap %}

{% block content %}

<form method="post" action="{% url 'account:register' %}">
    {% csrf_token %}

    <div class="login-form">

        {% if form.errors %}
            {% include "partials/alert.html" with msj="Usuario y/o contraseña incorrecta" tag="danger" %}
        {% endif %}

        {{ form | bootstrap }}
        <input type="submit" value="Registrar" class="btn btn-success float-right">
       

</form>

<a class="btn btn-link" href="{% url 'login' %}">Login</a>

</div>

{% endblock %}

account/templates/user_data.html
{% extends "base.html" %}

{% load bootstrap %}

{% block content %}

{% if user.is_authenticated %}
    <ul>
        <li><strong>Usuario:</strong> {{ user.username }}</li>
        <li><strong>Email:</strong> {{ user.email }}</li>
        <li><strong>Autenticado:</strong> {{ user.is_authenticated }}</li>
        <li><strong>Anónimo:</strong> {{ user.is_anonymous }}</li>
    </ul>
{% else %}
    <p><a href="{% url 'login' %}">Login</a></p>
{% endif %}

{% endblock %}