djangovue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from restmanual import views as restmanual

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('api/', include('listelement.urls')),
    path('comment/', include('comment.urls')),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('store.urls')),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
    ),
    path('restmanual/demo',restmanual.manualJson),
    path('restmanual/', include('restmanual.urls')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

store/urls.py
from django.urls import path, include
from . import views

from django.contrib.sitemaps.views import sitemap
from .sitemap import ElementSitemap

sitemaps = {
    'sitemap': ElementSitemap
}

app_name='store'
urlpatterns = [
    path('', views.index, name='index'),
    path('product/pay/paypal/<int:pk>', views.make_pay_paypal, name='make_pay_paypal'),
    path('product/pay/paypal/<int:pk>/<str:code>', views.make_pay_paypal, name='make_pay_paypal'),
    path('product/paypal/success/<int:pk>', views.paypal_success, name='paypal_success'),
    path('product/paypal/success/<int:pk>/<str:code>', views.paypal_success, name='paypal_success'),
    path('product/paypal/cancel', views.paypal_cancel, name='paypal_cancel'),

    path('bought', views.bought, name='bought'),

    path('product/payed/detail/<int:pk>', views.detail_pay, name='detail_pay'),
    
    path('product/<int:pk>',views.DetailView.as_view(), name='detail'),
    #path('product/<slug:url_clean>',views.DetailView.as_view(), name='detail'),
    path('product/coupon_apply',views.coupon_apply, name='coupon_apply'),
    path('product/<slug:url_clean>',views.detail, name='detail'),
    path('product/<slug:url_clean>/<str:code>',views.detail, name='detail'),

    #carrito
    path('cart_detail', views.cart_detail, name='cart_detail'),
    path('cart_size', views.cart_size, name='cart_size'),
    path('cart_remove/<int:pk>', views.cart_remove, name='cart_remove'),
    path('add_to_cart/<int:pk>', views.add_to_cart, name='add_to_cart'),
    
    #path('product/<int:pk>/<slug:url_clean>',views.DetailView.as_view(), name='detail'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

listelement/models.py
from decimal import Decimal

from taggit.managers import TaggableManager

from django.db import models
from stdimage import StdImageField, JPEGField

from django.dispatch import receiver
from django.conf import settings

from django.urls import reverse

from django.utils.text import slugify

import os

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255)
    url_clean = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class Type(models.Model):
    title = models.CharField(max_length=255)
    url_clean = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class Element(models.Model):
    tags = TaggableManager()
    title = models.CharField(max_length=255)
    url_clean = models.SlugField(max_length=255,blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10,decimal_places=2, default=6.10) # 12345678.10
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.url_clean = slugify(self.title)
        super(Element, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('store:detail', args=[self.url_clean])

    def get_discount(self, coupon):
        return (coupon.discount / Decimal(100)) * self.price # 10 /100 = 0.1 * 10$ = 1$

    def get_price_after_discount(self, coupon):
        return self.price - self.get_discount(coupon)

    def __str__(self):
        return self.title

class ElementImages(models.Model):
    element = models.ForeignKey(Element,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    cover = JPEGField(upload_to='images/',variations={'custom': {'width': 550, 'height': 750, "crop": True}})
    base_cover_name = models.CharField(max_length=100, default='')
    base_cover_ext = models.CharField(max_length=5, default='')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):

        (root, ext) = os.path.splitext(self.cover.path)

        print(settings.MEDIA_ROOT)
        print(root)

        if(self.base_cover_name == ""):
            root = root.replace(settings.MEDIA_ROOT+"\\","images/")        
            self.base_cover_name = root

        self.base_cover_ext = ext

        super(ElementImages,self).save(*args, **kwargs)


@receiver(models.signals.post_delete, sender=ElementImages)
def auto_delete_file_on_delete(sender, instance, **kwargs):

    if instance.cover:
        if os.path.isfile(instance.cover.path):
            os.remove(instance.cover.path)
        
    (root, ext) = os.path.splitext(instance.cover.path)
    extra_file = root+".custom.jpeg"

    if os.path.isfile(extra_file):
        os.remove(extra_file)

@receiver(models.signals.pre_save, sender=ElementImages)
def auto_delete_file_on_change(sender, instance, **kwargs):

    if not instance.pk:
        return False

    try:
        old_file = ElementImages.objects.get(pk=instance.pk).cover
    except ElementImages.DoesNotExist:
        return False

    new_file = instance.cover
    if not old_file == new_file:
        if instance.cover:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)

                
        (root, ext) = os.path.splitext(old_file.path)
        extra_file = root+".custom.jpeg"

        if os.path.isfile(extra_file):
            os.remove(extra_file)

store/forms.py
from django import forms

from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name','lastname', 'email', 'body')

    def __init__(self,user,*args,**kwargs):
        super(MessageForm, self).__init__(*args,**kwargs)
        if user.is_authenticated:
            self.fields['name'].widget = forms.HiddenInput()
            self.fields['name'].required = False
            self.fields['lastname'].widget = forms.HiddenInput()
            self.fields['lastname'].required = False
            self.fields['email'].widget = forms.HiddenInput()
            self.fields['email'].required = False

class CouponForm(forms.Form):
    code = forms.CharField()
    element_id = forms.CharField(widget=forms.HiddenInput())

store/views.py
from django.shortcuts import render, redirect,reverse, get_object_or_404
from django.core.paginator import Paginator
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.conf import settings
from django.utils import timezone
from django.http import HttpResponseNotFound, JsonResponse

from taggit.models import Tag

#import paypalrestsdk
from paypalcheckoutsdk.core import PayPalHttpClient, SandboxEnvironment
from paypalcheckoutsdk.orders import OrdersCreateRequest, OrdersCaptureRequest
from paypalhttp import HttpError
from decimal import Decimal

import logging

from listelement.models import Element, Category

from .models import Payment, Coupon
from .forms import MessageForm, CouponForm

from cart.cart import Cart

# Create your views here.

def index(request):
    search = request.GET.get('search') if request.GET.get('search') else ''
    category_id = request.GET.get('category_id')
    category_id = int(category_id) if category_id else ''

    tag_id = request.GET.get('tag_id')
    tag_id = int(tag_id) if tag_id else ''

    if search:
        elements = Element.objects.prefetch_related('elementimages_set').filter(title__contains=search)
    else:
        elements = Element.objects.prefetch_related('elementimages_set')

    if category_id:
        elements = elements.filter(category_id=category_id)

    if tag_id:
        tag = get_object_or_404(Tag,id=tag_id)
        elements = elements.filter(tags__in=[tag])
    
    elements = elements.filter(type = 1)
    paginator = Paginator(elements, 3)
    categories = Category.objects.all()
    tags = Tag.objects.all()    

    page_number = request.GET.get('page')
    elements_page = paginator.get_page(page_number)

    return render(request, 'store/index.html', {'elements' : elements_page,
                                        'categories':categories, 
                                        'tags' : tags,
                                        'search':search, 
                                        'category_id':category_id,
                                        'tag_id':tag_id
                                        })

def detail(request, url_clean, code=None):

    #print(code)


    #coupon= None
    #if code:
    #    coupon = get_valid_coupon(code)
    coupon = get_valid_coupon(code) if code else None

    msj_coupon =''
    if (code == 'None' or coupon is None) and code is not None:
        # el cupon es invalido
        msj_coupon ='El cupón es inválido'
        code = ''
        
    element = get_object_or_404(Element, url_clean=url_clean)

    if request.method == 'GET' and request.GET.get('quantity'):
        cart = Cart(request)
        cart.add(element, int(request.GET.get('quantity')))
        return redirect('store:detail',url_clean=element.url_clean)
        #for c in cart: print(c)


    messages = element.element_comments.filter(active=True)
    message_form = MessageForm(user=request.user)
    coupon_form = CouponForm(initial={'element_id':element.id,'code':code})
    message_new = None

    if request.method == 'POST':
        message_form = MessageForm(user=request.user,data=request.POST)
        if message_form.is_valid():
            message_new = message_form.save(commit=False)
            message_new.element = element
            if request.user.is_authenticated:
                message_new.name = request.user.first_name
                message_new.lastname = request.user.last_name
                message_new.email = request.user.email
                message_new.user = request.user
            message_new.save()
            message_form = MessageForm(user=request.user)

    cart = Cart(request)

    return render(request,'store/detail.html',{'element':element,
                                                'incart' : cart.getItem(element.id),
                                                'message_form': message_form,
                                                'message_new': message_new,
                                                'messages': messages,
                                                'coupon_form':coupon_form,
                                                'coupon': coupon,
                                                'msj_coupon':msj_coupon
    })

@require_POST
def coupon_apply(request):

    form = CouponForm(request.POST)
    coupon=None

    if form.is_valid():
        code = form.cleaned_data['code']
        elementId = form.cleaned_data['element_id']

    try:
        couponModel = get_valid_coupon(code)

        if couponModel:
            coupon = couponModel.code

    except Coupon.DoesNotExist:
        pass

    try:
        element = Element.objects.get(id=elementId)
    except Element.DoesNotExist:
        coupon=None

    return redirect('store:detail',url_clean=element.url_clean, code=coupon)


class DetailView(generic.DeleteView):
    model = Element
    template_name = 'store/detail.html'
    slug_field = 'url_clean'
    slug_url_kwarg = 'url_clean'

@login_required
def make_pay_paypal(request, pk, code=None):

    coupon = get_valid_coupon(code) if code else None

    #cupon invalido
    if coupon is None and code is not None:
        return HttpResponseNotFound()

    element = get_object_or_404(Element,pk = pk)

    if coupon:
        return_url = "http://127.0.0.1:8000/product/paypal/success/%s/%s"%(element.id,coupon.code)
        price = round(element.get_price_after_discount(coupon),2)
    else:
        return_url = "http://127.0.0.1:8000/product/paypal/success/%s"%element.id
        price = element.price

    client_id = settings.PAYPAL_CLIENT_ID
    client_secret = settings.PAYPAL_CLIENT_SECRET

    # Creating an environment
    environment = SandboxEnvironment(client_id=client_id, client_secret=client_secret)
    client = PayPalHttpClient(environment)

    requestPayPal = OrdersCreateRequest()

    requestPayPal.prefer('return=representation')

    requestPayPal.request_body (
        {
            "intent": "CAPTURE",
            "purchase_units": [
                {
                    "amount": {
                        "currency_code": "USD",
                        "value": str(price)
                    }
                }
            ],
            "application_context": {
                "return_url": return_url,
                "cancel_url": "http://127.0.0.1:8000/product/paypal/cancel"
            }
        }
    )

    try:
        # Call API with your client and get a response for your call
        response = client.execute(requestPayPal)

        if response.result.status == "CREATED":
            approval_url = str(response.result.links[1].href)
            print(approval_url)

            return render(request,'store/paypal/buy.html',{'element': element, 'approval_url':approval_url })

    except IOError as ioe:
        print (ioe)
        if isinstance(ioe, HttpError):
            # Something went wrong server-side
            print (ioe.status_code)


@login_required
def paypal_success(request,pk,code=None):

    coupon = get_valid_coupon(code) if code else None

    client_id = settings.PAYPAL_CLIENT_ID
    client_secret = settings.PAYPAL_CLIENT_SECRET

    # Creating an environment
    environment = SandboxEnvironment(client_id=client_id, client_secret=client_secret)
    client = PayPalHttpClient(environment)

    element = get_object_or_404(Element, pk = pk)

    ordenId = request.GET.get('token')
    payerId = request.GET.get('PayerID')

    requestPayPal = OrdersCaptureRequest(ordenId)

    try:
        # Call API with your client and get a response for your call
        response = client.execute(requestPayPal)

        paymentModel = Payment.create(payment_id=ordenId, 
            payer_id=payerId,
            price=element.price,
            element_id=element.id,
            user_id=request.user.id
        )

        if coupon:
            paymentModel.coupon = coupon
            paymentModel.discount = element.get_price_after_discount(coupon)
            paymentModel.price_discount = element.get_discount(coupon)
            coupon.active = 0
            coupon.save()

        paymentModel.save()

        # If call returns body in response, you can get the deserialized version from the result attribute of the response
        order = response.result.id
    except IOError as ioe:
        if isinstance(ioe, HttpError):
            # Something went wrong server-side
            print (ioe.status_code)
            print (ioe.headers)
            print (ioe)
        else:
            # Something went wrong client side
            print (ioe)

    return render(request,'store/paypal/success.html')



@login_required
def make_pay_paypal_old(request, pk, code=None):

    coupon = get_valid_coupon(code) if code else None

    #cupon invalido
    if coupon is None and code is not None:
        return HttpResponseNotFound()

    element = get_object_or_404(Element,pk = pk)

    if coupon:
        return_url = "http://127.0.0.1:8000/product/paypal/success/%s/%s"%(element.id,coupon.code)
        price = round(element.get_price_after_discount(coupon),2)
    else:
        return_url = "http://127.0.0.1:8000/product/paypal/success/%s"%element.id
        price = element.price

    paypalrestsdk.configure({
    "mode": settings.PAYPAL_CLIENT_MODO, 
    "client_id": settings.PAYPAL_CLIENT_ID,
    "client_secret":  settings.PAYPAL_CLIENT_SECRET})

    payment = paypalrestsdk.Payment({
        "intent": "sale",
        "payer": {
            "payment_method": "paypal"},
        "redirect_urls": {
            "return_url": return_url,
            "cancel_url": "http://127.0.0.1:8000/product/paypal/cancel"},
        "transactions": [{
            "amount": {
                "total": str(price),
                "currency": "USD"},
            "description": "This is the payment transaction description."}]})

    if payment.create():

store/templates/store/detail.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block content %}
<div class="card mt-2 cardDetail">
  <div class="card-body">

    <div class="row">
      <div class="col-md-4">

        {% if element.elementimages_set.all.count %}
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">

            {% for i in element.elementimages_set.all %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}"
              class="{{ forloop.counter0|yesno:',active,' }}"></li>
            {% endfor %}
          </ol>
          <div class="carousel-inner">

            {% for i in element.elementimages_set.all %}
            <div class="carousel-item {{ forloop.counter0|yesno:',active,' }}">
              <img src="/uploads/{{ i.base_cover_name }}.custom.jpeg" class="d-block w-100" alt="{{ i.title }}"
                title="{{ i.title }}">
            </div>
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        {% else %}
        <img class="d-block w-100" src="/uploads/images/default.jpeg" alt="Imagen por defecto"
          title="Imagen por defecto">
        {% endif %}

        {% if incart %}
          <a href="{% url 'store:cart_detail' %}" class="btn btn-info btn-sm mt-2"><i class="fa fa-eye"></i> Ver en el carrito</a>
        {% endif %}

      </div>

      <div class="col-md-8">
        <div class="col-12">
          <h1 class="text-center" id="title">{{ element.title }}</h1>
        </div>

        <div class="row">
          <div class="col-md-6">
            <p class="text-muted"><small>{{ element.tags.all|join:", " }}</small></p>
          </div>
          <div class="col-md-6">
            {% with messages.count as total_comments %}
            <h6>
              {{ total_comments }} <i class="fa fa-comment text-danger"></i> comentario{{ total_comments|pluralize }}
            </h6>
            {% endwith %}
          </div>
        </div>


        <hr>


        <span class="float-right">{{ element.price }}$</span>

        <label class="b-block">Agregar al carrito</label>
        <form class="form-inline">
          <div class="form-group">
            <input required type="number" name="quantity" class="form-control mr-1" placeholder="Cantidad" value="1">
            <button class="btn btn-secondary">Agregar</button>
          </div>
        </form>

        {% if coupon %}
        <a class="btn btn-primary btn-sm mt-2 mb-1 ml-1" href="{% url 'store:make_pay_paypal' element.id coupon.code %}">
          <i class="fab fa-paypal"></i>
          PayPal
        </a>
        {% else %}
        <a class="btn btn-primary btn-sm mt-2 mb-1 ml-1" href="{% url 'store:make_pay_paypal' element.id %}">
          <i class="fab fa-paypal"></i>
          PayPal
        </a>
        {% endif %}
        

        <div class="row">
          <div class="col-12">
            {% if coupon %}
              {% include "store/fragment/detail_coupon.html" %}
            {% endif %}
          </div>
        </div>
      

        <details class="mb-4 ml-2 coupon">
          <summary><small class="text-muted">
            ¿Tienes un cupón?

            {% if msj_coupon %}
              <span class="text-danger">{{ msj_coupon }}</span>
            {% endif %}

          </small></summary>
          
          <form id="coupon" action="{% url 'store:coupon_apply' %}" method="POST" class="form-inline mt-2 bg-light p-2">

            {% csrf_token %}

            {{ coupon_form|bootstrap }}
            <button type="submit" class="btn btn-primary ml-2"><i class="fa fa-check"></i></button>
          </form>

        </details>

        <p>{{ element.description }}</p>
      </div>

    </div>


  </div>
</div>

<div class="card cardDetail mt-3">
  <div class="card-header">
    <i class="fa fa-comment"></i> Comentarios
  </div>
  <div class="card-body">
    {% for m in messages %}
    <div class="comment">
      <p>
        <strong>
          Comentario {{ m.counter }} por {{ m.name }} {{ m.created }}:
        </strong>

        {{ m.body }}
      </p>
    </div>

    {% empty %}
    <p>Sin comentarios.</p>
    {% endfor %}
  </div>
  <div class="card-header border-top">
    Comentar
  </div>
  <div class="card-body">

    <form action="" method="post">

      {% csrf_token %}

      {% include 'partials/form_errors.html' with form=message_form %}

      {{ message_form|bootstrap }}
      <input type="submit" value="Enviar" class="btn btn-primary">
    </form>

  </div>

</div>

{% endblock %}



{% include 'partials/pagination.html' with page_obj=elements %}

store/templates/store/index.html
{% extends 'base.html' %}

{% block content %}

<form method="get" class="form-inline justify-content-center" id="filterStore">
  <input placeholder="Buscar..." class="form-control form-control-sm w-25" type="text" value="{{ search }}" name="search">

  <select name="category_id" class="w-25 form-control form-control-sm">
    <option value="">Sin selección</option>
    {% for c in categories %}
    <option {% if category_id == c.id %} selected {% endif %} value="{{ c.id }}">{{ c.title }}</option>
    {% endfor %}
  </select>

  <select name="tag_id" class="w-25 form-control form-control-sm">
    <option value="">Sin selección</option>
    {% for t in tags %}
    <option {% if tag_id == t.id %} selected {% endif %} value="{{ t.id }}">{{ t.name }}</option>
    {% endfor %}
  </select>

  <button class="btn btn-primary btn-sm" type="submit"><i class="fas fa-search"></i></button>
</form>

<div class="row">
  <div class="col-12">
    <h2 id="title" class="text-center mt-3">Productos de la tienda</h2>
  </div>
</div>

<div class="row">


  {% for e in elements %}
  <div class="col-xl-3 col-lg-4 col-md-4 col-12">
    <div class="single-product">
      <div class="product-img">
        <a href="{% url 'store:detail' e.url_clean %}">

          {% if e.elementimages_set.all.count %}
          <img src="uploads/{{ e.elementimages_set.all.0.base_cover_name }}.custom.jpeg"
            alt="{{ e.elementimages_set.all.0.title }}" title="{{ e.elementimages_set.all.0.title }}">
          {% else %}
          <img src="uploads/images/default.jpeg" alt="Imagen por defecto" title="Imagen por defecto">
          {% endif %}



        </a>
      </div>
      <div class="product-content">
        <h3>
          <a href="{% url 'store:detail' e.url_clean %}">{{ e.title }}</a>
        </h3>
        <div class="product-price">
          ${{ e.price }}
        </div>
      </div>

    </div>

  </div>
  {% endfor %}
</div>

{% include 'partials/pagination.html' with page_obj=elements %}

{% endblock %}

store/templates/store/index_old.html
{% extends 'base.html' %}

{% block content %}

    <form method="get" class="form-inline justify-content-center">
      <input class="w-50 mr-2" type="text" value="{{ search }}" name="search" class="form-control form-control-sm">

      <select name="category_id" class="w-25 form-control form-control-sm mr-2">
        <option value="">Sin selección</option>
        {% for c in categories %}
          <option 
          
          {% if category_id == c.id %} selected {% endif %}
          
          
          value="{{c.id}}">{{c.title}}</option>
        {% endfor %}
      </select>

      <button class="btn btn-primary btn-sm" type="submit">Buscar</button>
    </form>

    {% for e in elements %}
      <div class="card mt-2">
          <div class="card-header bg-success"></div>
          <div class="card-body">
            <h3>{{ e.title }}</h3>
            <p>{{ e.description|truncatechars:'150' }}</p>

             <a class="btn btn-success btn-sm float-right" href="{% url 'store:detail' e.id %}">Ver ID</a>
             <a class="btn btn-success btn-sm float-right" href="{% url 'store:detail' e.url_clean %}">Ver Slug</a>   
             <a class="btn btn-success btn-sm float-right" href="{% url 'store:detail' e.id e.url_clean %}">Ver ID y Slug</a>   

          </div>
          
      </div>
    {% endfor %}

{% endblock %}



{% include 'partials/pagination.html' with page_obj=elements %}