comment/urls.py
from django.urls import path
from . import views

app_name='comment'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('contact', views.contact, name='contact'),
    path('export', views.export, name='export'),
    path('update/<int:pk>', views.update, name='update'),

    path('testview', views.testview),
]

djangovue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from restmanual import views as restmanual

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('api/', include('listelement.urls')),
    path('comment/', include('comment.urls')),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('store.urls')),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
    ),
    path('restmanual/demo',restmanual.manualJson),
    path('restmanual/', include('restmanual.urls')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

store/urls.py
from django.urls import path, include
from . import views

from django.contrib.sitemaps.views import sitemap
from .sitemap import ElementSitemap

sitemaps = {
    'sitemap': ElementSitemap
}

app_name='store'
urlpatterns = [
    path('', views.index, name='index'),
    path('product/pay/paypal/<int:pk>', views.make_pay_paypal, name='make_pay_paypal'),
    path('product/pay/paypal/<int:pk>/<str:code>', views.make_pay_paypal, name='make_pay_paypal'),
    path('product/paypal/success/<int:pk>', views.paypal_success, name='paypal_success'),
    path('product/paypal/success/<int:pk>/<str:code>', views.paypal_success, name='paypal_success'),
    path('product/paypal/cancel', views.paypal_cancel, name='paypal_cancel'),

    path('bought', views.bought, name='bought'),

    path('product/payed/detail/<int:pk>', views.detail_pay, name='detail_pay'),
    
    path('product/<int:pk>',views.DetailView.as_view(), name='detail'),
    #path('product/<slug:url_clean>',views.DetailView.as_view(), name='detail'),
    path('product/coupon_apply',views.coupon_apply, name='coupon_apply'),
    path('product/<slug:url_clean>',views.detail, name='detail'),
    path('product/<slug:url_clean>/<str:code>',views.detail, name='detail'),

    #carrito
    path('cart_detail', views.cart_detail, name='cart_detail'),
    path('cart_size', views.cart_size, name='cart_size'),
    path('cart_remove/<int:pk>', views.cart_remove, name='cart_remove'),
    path('add_to_cart/<int:pk>', views.add_to_cart, name='add_to_cart'),
    
    #path('product/<int:pk>/<slug:url_clean>',views.DetailView.as_view(), name='detail'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

comment/models.py
from django.db import models
from listelement.models import Element
# Create your models here.

class Comment(models.Model):
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    element = models.ForeignKey(Element, related_name='comments', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return 'Comentario #{}'.format(self.id)

class TypeContact(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Contact(models.Model):

    SEX = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otro')
    )

    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    email = models.CharField(max_length=70)
    phone = models.CharField(max_length=13)
    date_birth = models.DateField()
    document = models.FileField(upload_to='uploads/contact',default=None,null=True)
    sex = models.CharField(max_length=1, choices=SEX, default='M')
    type_contact = models.ForeignKey(TypeContact, on_delete=models.CASCADE, default=1)

comment/forms.py
from django.forms import ModelForm, Textarea

from .models import Comment, TypeContact

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text' : Textarea(attrs={'class':'form-input'})
        }
    '''def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({'class':'form-input'})'''
    def save(self,commit=True, text=""):
        instance = super(CommentForm, self).save(commit=commit)

        if(text != ""):
            instance.text= text#"No podrás modificarme"

        if(commit):
            instance.save()
        
        return instance

from django import forms
from django.core.validators import MinLengthValidator,EmailValidator

class ContactForm(forms.Form):

    SEX = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otro')
    )

    #name = forms.CharField(label="Nombre", initial='Pepe', required=True, disabled=False, help_text='Aquí va tu nombre y no el de tu tía', max_length=10, min_length=3)    
    name = forms.CharField(label="Nombre", max_length=10, min_length=3 ) #validators=[MinLengthValidator(2, message='Muy corto! (minino %(limit_value)d) actual %(show_value)d ')]   widget=forms.(attrs={'class':'form-control'})
    #email = forms.CharField(label='Correo', validators=[EmailValidator(message='Correo inválido', whitelist=['gmail'])])
    email = forms.EmailField(label='Correo', initial='andres@gmail.com')
    surname = forms.CharField(label="Apellido", required=False, max_length=10, min_length=3)    
    phone = forms.RegexField(label='Teléfono',regex='\(\w{3}\)\w{3}-\w{4}', max_length=13, min_length=13, initial='(123)123-1234')
    date_birth = forms.DateField(label='Fecha de nacimiento',initial='1990-11-29')
    #type_contact = forms.ChoiceField(label='Tipo de contacto', choices=CHOICE, initial=20)
    type_contact = forms.ModelChoiceField(label='Tipo de contacto', queryset=TypeContact.objects.all(), initial=2)
    sex = forms.ChoiceField(label='Sexo', choices=SEX)
    document = forms.FileField(label='Documento', required=False)
    tems = forms.BooleanField(label='Condiciones de servicio')
    
    

comment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.template import loader
from django.http import HttpResponse

from django.utils.translation import gettext as _


from .models import Comment,Contact
from .forms import CommentForm, ContactForm

import logging
import csv

# Get an instance of a logger
logger = logging.getLogger(__name__)

def export(request):
    _('Put your favorite email')
    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = 'attachment; filename="datostest.csv"'

    comments = Comment.objects.all()

    writer = csv.writer(response)

    writer.writerow(["Id","Comentario"])
    for c in comments:
        writer.writerow([c.id,c.text])

    #writer.writerow(['Primera fila','Django','Flask','Python'])
    #writer.writerow(['Primera fila','A','B','C','Más datos','Otro'])

    return response


def testview(request):
    return render(request,'test/testview.html')

def index(request):
    print(_("Welcome to my app"))
    logger.debug('...debug')
    logger.info('...info')
    logger.error('...error')

    if 'comment_id' in request.session:
        print("Último comentario "+str(request.session['comment_id']))
        del request.session['comment_id']

    comments = Comment.objects.all()
    paginator = Paginator(comments,5)

    page_number = request.GET.get('page')
    comments_page = paginator.get_page(page_number)

    #return render(request,'index.html',{'comments':comments})
    return render(request,'index_page.html',{'comments_page':comments_page})

def add(request):

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save()

            html_message = loader.render_to_string('email/comment.html',{'comment': comment})

            request.session['comment_id'] = comment.id

            send_mail(
                "Comentario #"+str(comment.id), #"Título", 
                comment.text,#"Contenido del mail",
                "andres@gmail.com",
                ["juan@gmail.com"],
                fail_silently=False,
                html_message=html_message
                #html_message="<h1>Hola Mundo</h1>"
                )

            return redirect('comment:index')
    else:
        form = CommentForm()

    return render(request,'add.html',{'form':form})

def update(request, pk):

    comment = get_object_or_404(Comment, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)

        print(form.errors.as_text())

        if form.is_valid():
            form.save(commit=True,text="Hola Mundo")
            return redirect('comment:update',pk=comment.id)
    else:
        form = CommentForm(instance=comment)

    return render(request,'update.html',{'form':form, 'comment': comment})

from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ValidationError

@csrf_exempt
def contact(request):

    if request.method == 'POST':
        form = ContactForm(request.POST,request.FILES)

        if form.is_valid():

            contact = Contact()
            contact.name = form.cleaned_data['name']
            contact.surname = form.cleaned_data['surname']
            contact.phone = form.cleaned_data['phone']
            contact.email = form.cleaned_data['email']
            contact.date_birth = form.cleaned_data['date_birth']
            contact.sex = form.cleaned_data['sex']
            contact.type_contact = form.cleaned_data['type_contact']
            if 'document' in request.FILES:
                contact.document = request.FILES['document']
            contact.save()

            messages.add_message(request, messages.INFO, 'Contacto recibido!')
            
            return redirect('comment:contact')
        else:
            print('Inválido')

    else:
        form = ContactForm()

    
    

    #if(form.errors):
    #    raise ValidationError(form.errors)

    return render(request,'contact.html',{'form':form})

comment/templates/add.html
{% extends "base.html" %}

{% block content %}

{% load i18n %}

    <form action="{% url 'comment:add' %}" method="post">

    {% trans 'Put your favorite email' %}

        {% csrf_token %}

        {{ form.text }}

        <input type="submit" value="Enviar">

    </form>

    <style>
        .form-input {
            width:  100%;
        }
    </style>

{% endblock %}

comment/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">

</head>

<body>

    {% include "partials/header.html" %}

    <div class="container my-3">
        {% block content %}

        {% endblock %}
    </div>

    {% include "partials/footer.html" %}

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/store.js' %}"></script>

</body>

</html>

comment/templates/base_user_account.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/user.style.css' %}">

</head>

<body>

<div class="sidenav">
         <div class="login-main-text">
            <h2>Application<br> Login Page</h2>
            <p>Login or register from here to access.</p>
         </div>
      </div>
      <div class="main">
         <div class="col-md-9 col-sm-12">


        {% block content %}

        {% endblock %}
 

           
         </div>
      </div>

  



    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

</body>

</html>

comment/templates/contact.html
{% extends "base.html" %}

{% load bootstrap %}

{% block content %}

<div class="card">
    <div class="card-header">
        <h3>Contacto</h3>
    </div>
    <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">


            {% if form.errors %}
            <br>
            {% for field in form  %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.name }}:</strong> {{ error }}
            </div>
            {% endfor %}
            {% endfor %}
            {% endif %}

            {{ form|bootstrap }}
            <input type="submit" value="Enviar" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock %}

comment/templates/index.html
{% extends "base.html" %}


{% block content %}

<!-- comentario HTML -->

{# comentario #}

    {% for c in comments %}
      <div>
          {% autoescape off %}
          {% endautoescape %}
          {{ c.text|escape }}
            --
          {{ c.date_posted|date:"D d M Y" }}

          {% comment 'esto es un comentario' %}
            <p> Hola mundo </p>
          {% endcomment  %}
          
      </div>
    {% endfor %}

<table>
    {% for c in comments %}
        <tr class="{% cycle 'row1' 'row2' 'row3' %}">
            ...
        </tr>
    {% endfor %}
</table>

{{ 5|add:"3" }}

{{ "ANDRES"|lower }}

{% endblock %}

comment/templates/index_page.html
{% extends "base.html" %}


{% block content %}

<!-- comentario HTML -->

{# comentario #}

    {% for c in comments_page %}
      <div>
          {% autoescape off %}
          {% endautoescape %}
          {{ c.text|escape }}
            --
          {{ c.date_posted|date:"D d M Y" }}

          {% comment 'esto es un comentario' %}
            <p> Hola mundo </p>
          {% endcomment  %}
          
      </div>
    {% endfor %}

<table>
    {% for c in comments_page %}
        <tr class="{% cycle 'row1' 'row2' 'row3' %}">
            ...
        </tr>
    {% endfor %}
</table>

{% include 'partials/pagination.html' with page_obj=comments_page %}

{{ 5|add:"3" }}

{{ "ANDRES"|lower }}

{% endblock %}

comment/templates/update.html
{% extends "base.html" %}

{% block content %}

    {{ form.errors }}
    
    <form action="{% url 'comment:update' comment.id %}" method="post">

        {% csrf_token %}

        {{ form.text }}

        <input type="submit" value="Enviar">

    </form>

    <style>
        .form-input {
            width:  100%;
        }
    </style>
{% endblock %}